### ISSUE TITLE
[Feature] APPLE MUSIC SUPPORT

### ISSUE THREAD

**Issue by YV0112** [trumully/dynamo#16]
### Feature Description

ADD APPLE MUSIC SUPPORT NOW.

### Implementation

- LOOK THROUGH CIDER API
- PICK ONE AND IMPLIMENT

### Additional Context

https://github.com/ciderapp/Cider-Bot
https://github.com/ciderapp/

**Comment by trumully** [comment]
Annual fee of $149 no thanks
